# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15d816d05a75ddda297cc01c864badde8ceba636c0fcef276c06155a807f370e7d01f6c4db908170c9471d24e5daafab9b29d7c5b872e6e477a9a5dc1b6b0e23

test:
  secret_key_base: ba17ab574f3f720c4e2d84dd9e049c23b05cdaada0ef37b0b3957b04cb0659f392492b2930b0a252f166594ecf6c74a784cf378343da27f0b57cfb18e69d08d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
